apiVersion: v1
kind: Service
metadata:
    name: "cluster-0fed"
    labels:
        app: "cluster-0fed"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "cluster-0fed"